version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "joinus"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-14ezuchw5mu78"
s3_prefix = "joinus"
region = "ap-south-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"

