AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: SQS -> Lambda -> DB

Globals:
  Function:
    Timeout: 30

Resources:
  JoinUsFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      FunctionName: joinus
      CodeUri: worker/
      Handler: app.lambda_handler
      Runtime: python3.8
      Role: arn:aws:iam::996119619820:role/sqs_lambda
      Events:
        JoinUsEvents:
          Type: SQS
          Properties:
            Queue: arn:aws:sqs:ap-south-1:996119619820:flow_queue
            BatchSize: 1
            Enabled: true

Outputs:
  JoinUsFunction:
    Description: "JoinUsFunction Lambda Function ARN"
    Value: !GetAtt JoinUsFunction.Arn
  JoinUsEvents:
    Description: "JoinUsEvents ARN"
    Value: !Sub JoinUsEvents.Arn
